server:
  port: 10010
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://114.55.108.153:3306/idss_app_weiark_maoyan_test?useUnicode=true&characterEncoding=utf-8
    username: idss
    password: 13eE_feb7940a